name: dynocsv # you probably want to 'snapcraft register <name>'
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Exports DynamoDB table into CSV # 79 char long summary
description: |
    Exports DynamoDB table into CSV, additionally can filter out the specific columns to be exported.

base: core18
confinement: strict # use 'strict' once you have the right plugs and slots
grade: stable # must be 'stable' to release into candidate/stable channels

parts:
  dynocsv:
    plugin: go
    go-importpath: github.com/zshamrock/dynocsv
    source: .
    source-type: git

apps:
  dynocsv:
    command: dynocsv