name: dynocsv # you probably want to 'snapcraft register <name>'
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Exports DynamoDB table into CSV # 79 char long summary
description: |
  Exports DynamoDB table into CSV, additionally can filter out specific columns and limit the number of items to be exported.

  The tool relies on reading AWS profile config credentials (`$HOME/.aws`), so when installed you would need explicitly allow this access by running:

  `snap connect dynocsv:aws-config-credentials`

confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
#grade: stable # must be 'stable' to release into candidate/stable channels
grade: stable
license: MIT

parts:
  dynocsv:
    plugin: go
    #    source-type: git
    source-type: local
    #    source: https://github.com/zshamrock/dynocsv
    source: .
    go-importpath: github.com/zshamrock/dynocsv
    build-packages:
      - gcc
      - git

plugs:
  aws-config-credentials:
    interface: personal-files
    read:
      - $HOME/.aws/config
      - $HOME/.aws/credentials

apps:
  dynocsv:
    command: dynocsv
    plugs:
      - network
      - removable-media
      - home
      - aws-config-credentials
